// The Tier-1 scheduler — runs jobs locally on their cron, and exports the same job set to a
// real Airflow DAG or GitHub Actions workflow. Define the schedule once; run it wherever the
// environment allows (a laptop loop, Airflow in the enclave, or Actions in CI).
import { matches, nextRun } from "./cron.mjs";

export { parseCron, matches, nextRun } from "./cron.mjs";

export class Scheduler {
  constructor() { this.jobs = []; }
  /** @param {{name, cron, run?:Function}} job */
  register(job) { this.jobs.push(job); return this; }

  /** Jobs whose cron matches `now` (to the minute, UTC). */
  due(now) { return this.jobs.filter((j) => matches(j.cron, now)); }

  /** Run every due job; returns [{name, result}]. */
  async runDue(now) {
    const ran = [];
    for (const j of this.due(now)) ran.push({ name: j.name, result: j.run ? await j.run() : null });
    return ran;
  }

  /** Next firing per job — handy for a status view. */
  upcoming(after) { return this.jobs.map((j) => ({ name: j.name, next: nextRun(j.cron, after) })); }
}

const slug = (s) => s.replace(/[^a-z0-9]+/gi, "_").toLowerCase();
const q = (s) => `'${String(s).replace(/'/g, "\\'")}'`;
const cmdFor = (job, runner) => `node ${runner} ${job.name}`;

/**
 * Emit a Python file defining one Airflow DAG per job (each with its own schedule).
 * @param {Array} jobs   from @aigovops/agents TIER1_JOBS
 * @param {{runner?:string, startDate?:[number,number,number]}} [opts]
 */
export function toAirflowDags(jobs, { runner = "packages/agents/src/run.mjs", startDate = [2026, 1, 1] } = {}) {
  const header =
    "# Generated by @aigovops/scheduler — Tier-1 autonomous agents. Do not edit by hand.\n" +
    "from airflow import DAG\nfrom airflow.operators.bash import BashOperator\nimport datetime\n\n";
  const blocks = jobs.map((j) =>
    `with DAG(\n` +
    `    dag_id=${q("aigovops_" + slug(j.name))},\n` +
    `    schedule_interval=${q(j.cron)},\n` +
    `    start_date=datetime.datetime(${startDate.join(", ")}),\n` +
    `    catchup=False,\n` +
    `    tags=['aigovops', 'tier1'],\n` +
    `) as dag_${slug(j.name)}:\n` +
    `    ${slug(j.name)} = BashOperator(\n` +
    `        task_id=${q(j.name)},\n` +
    `        bash_command=${q(cmdFor(j, runner))},\n` +
    `    )\n`,
  );
  return header + blocks.join("\n");
}

/** Emit a GitHub Actions workflow with one scheduled job per agent. */
export function toGithubActionsWorkflow(jobs, { runner = "packages/agents/src/run.mjs" } = {}) {
  const lines = [
    "# Generated by @aigovops/scheduler — Tier-1 autonomous agents.",
    "name: tier1-agents",
    "on:",
    "  workflow_dispatch:",
    "  schedule:",
    ...[...new Set(jobs.map((j) => j.cron))].map((c) => `    - cron: ${q(c)}`),
    "permissions: { contents: read }",
    "jobs:",
  ];
  for (const j of jobs) {
    lines.push(
      `  ${slug(j.name)}:`,
      `    runs-on: ubuntu-latest`,
      `    steps:`,
      `      - uses: actions/checkout@v4`,
      `      - uses: actions/setup-node@v4`,
      `        with: { node-version: 20 }`,
      `      - run: ${cmdFor(j, runner)}`,
    );
  }
  return lines.join("\n") + "\n";
}
