// M10 — the Docker Compose generator. Zero-dependency.
//
// Maps a deployment tier (+ explicit extras) to the set of Apache-2.0 backends to start, and emits
// a valid compose file. Tiers 1–2 run the gate alone; 3+ add the heavyweight stack the M4 adapters
// route to. Caddy fronts everything with automatic HTTPS so the 1-click paths are TLS-secured.

const GATE_PORT = 8930;

// Which backends each tier brings up (the gate is always present).
const TIER_SERVICES = {
  1: [], 2: [], 3: ["opensearch"],
  4: ["keycloak", "opensearch", "prometheus"],
  5: ["keycloak", "opensearch", "prometheus"],
  6: ["keycloak", "opensearch", "prometheus"],
};

const SERVICE_DEFS = {
  gate: (port) => ({
    image: "aigovops/studio:4.0.0",
    build: "../..",
    ports: [`${port}:${GATE_PORT}`],
    environment: [`PORT=${GATE_PORT}`, "AIGOVOPS_TIER=${AIGOVOPS_TIER:-4}"],
    restart: "unless-stopped",
  }),
  caddy: () => ({
    image: "caddy:2-alpine",
    ports: ["80:80", "443:443"],
    volumes: ["./Caddyfile:/etc/caddy/Caddyfile", "caddy_data:/data"],
    depends_on: ["gate"],
    restart: "unless-stopped",
  }),
  keycloak: () => ({
    image: "quay.io/keycloak/keycloak:26.0",
    command: "start-dev",
    environment: ["KC_BOOTSTRAP_ADMIN_USERNAME=admin", "KC_BOOTSTRAP_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-admin}"],
    ports: ["8080:8080"],
    restart: "unless-stopped",
  }),
  opensearch: () => ({
    image: "opensearchproject/opensearch:2.16.0",
    environment: ["discovery.type=single-node", "DISABLE_SECURITY_PLUGIN=true", "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"],
    ports: ["9200:9200"],
    restart: "unless-stopped",
  }),
  prometheus: () => ({
    image: "prom/prometheus:v2.54.0",
    ports: ["9090:9090"],
    restart: "unless-stopped",
  }),
};

/** The full list of services (deduped) for a tier + explicit extras. */
export function servicesFor({ tier = 1, withServices = [] } = {}) {
  return [...new Set([...(TIER_SERVICES[tier] || []), ...withServices])];
}

/** Build the compose object. Caddy is added whenever any backend (or a domain) is present. */
export function composeFor({ tier = 1, withServices = [], port = GATE_PORT } = {}) {
  const extras = servicesFor({ tier, withServices });
  const services = { gate: SERVICE_DEFS.gate(port) };
  if (extras.length) services.caddy = SERVICE_DEFS.caddy();
  for (const s of extras) if (SERVICE_DEFS[s]) services[s] = SERVICE_DEFS[s]();
  const compose = { name: "aigovops", services };
  if (services.caddy) compose.volumes = { caddy_data: null };
  return compose;
}

/** A Caddyfile that fronts the gate with automatic HTTPS (or :80 for a local/no-domain run). */
export function caddyfileFor({ domain } = {}) {
  const site = domain || ":80";
  return `${site} {\n\treverse_proxy gate:${GATE_PORT}\n}\n`;
}

// --- minimal, correct YAML emitter (maps · scalar arrays · scalars) ---------
function scalar(v) {
  if (v === null || v === undefined) return "";
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  const s = String(v);
  // Quote anything risky for YAML — notably any value with a colon (ports, volumes, env defaults).
  return s === "" || s.includes(":") || /^[\s>|*&!%@`"#,{}\[\]]|\s$/.test(s) ? JSON.stringify(s) : s;
}

export function toYaml(value, indent = 0) {
  const pad = "  ".repeat(indent);
  if (Array.isArray(value)) {
    return value
      .map((item) => {
        if (item && typeof item === "object") {
          // Block sequence of maps: render the map one level deeper, then turn its first line into "- ".
          const lines = toYaml(item, indent + 1).split("\n");
          lines[0] = pad + "- " + lines[0].slice((indent + 1) * 2);
          return lines.join("\n");
        }
        return `${pad}- ${scalar(item)}`;
      })
      .join("\n");
  }
  if (value && typeof value === "object") {
    return Object.entries(value)
      .map(([k, val]) => {
        if (Array.isArray(val)) return val.length ? `${pad}${k}:\n${toYaml(val, indent + 1)}` : `${pad}${k}: []`;
        if (val && typeof val === "object") return `${pad}${k}:\n${toYaml(val, indent + 1)}`;
        return `${pad}${k}:${val === null ? "" : " " + scalar(val)}`;
      })
      .join("\n");
  }
  return `${pad}${scalar(value)}`;
}

/** The complete docker-compose.yml text for a tier. */
export function composeYaml(opts) {
  return "# Generated by `aigovops up` — AiGovOps gate stack.\n" + toYaml(composeFor(opts)) + "\n";
}
